#!/usr/bin/env python3
# SectorFlux - LLM Proxy and Analytics
# Copyright (c) 2025 ParticleSector.com
#
# This software is dual-licensed:
# - GPL-3.0 for open source use
# - Commercial license for proprietary use
#
# See LICENSE and LICENSING.md for details.

"""
Embed UI files into a C++ header for single-binary distribution.

This script converts HTML, CSS, and JS files into C++ byte arrays
that can be included directly in the SectorFlux binary.
"""

import os


def file_to_hex(filepath: str, var_name: str) -> str:
    """Convert a file to a C++ hex array declaration."""
    with open(filepath, 'rb') as f:
        content = f.read()

    hex_array = ', '.join([f'0x{b:02x}' for b in content])
    return (
        f'const unsigned char {var_name}[] = {{ {hex_array} }};\n'
        f'const size_t {var_name}_len = {len(content)};\n'
    )


def main() -> None:
    """Main entry point for the embed script."""
    script_dir = os.path.dirname(__file__)
    public_dir = os.path.join(script_dir, '..', 'public')
    output_file = os.path.join(script_dir, '..', 'src', 'embedded_ui.hpp')

    files_to_embed = {
        'index.html': 'index_html',
        'app.js': 'app_js',
        'api.js': 'api_js',
        'style.css': 'style_css'
    }

    with open(output_file, 'w') as out:
        out.write('#pragma once\n\n')
        out.write('// Auto-generated file - do not edit manually\n')
        out.write('// Generated by scripts/embed_ui.py\n\n')
        out.write('#include <cstddef>\n\n')

        for filename, var_name in files_to_embed.items():
            filepath = os.path.join(public_dir, filename)
            if os.path.exists(filepath):
                out.write(file_to_hex(filepath, var_name))
                out.write('\n')
                print(f'Embedded {filename} as {var_name}')
            else:
                print(f'Warning: {filename} not found at {filepath}')


if __name__ == '__main__':
    main()
